### ISSUE TITLE
started

### ISSUE THREAD

**Issue by cx4** [McGill-NLP/webllama#13]
I don't understand how to get started quickly. Could you provide a simple example?

**Comment by xhluca** [comment]
Check out this PR, with new added feature (you can install the pre-release from pypi): https://github.com/McGill-NLP/webllama/pull/12

**Comment by xhluca** [comment]
@tianwang2021 should be fixed now, i just pushed a fix.

**Comment by xhluca** [comment]
You might also want to consider updating the image if you want to keep your IP address private.

**Comment by tianwang2021** [comment]
好的谢谢您

**Comment by cx4** [comment]
> @tianwang2021 should be fixed now, i just pushed a fix.

I tried to run it on June 25th , and still didn't work.

**Comment by cx4** [comment]
> @cx4 Seems I missed a few. I've made another change on this commit: [cef6b96](https://github.com/McGill-NLP/webllama/commit/cef6b96dcbb66816c73fd35db656eb9da9c9c0fe)
> 
> Can you pull from main again and try?

@xhluca Line 15th of th `run_all.py` file mentions the tests directory. what files should I put in ?

**Comment by xhluca** [comment]
https://github.com/McGill-NLP/webllama/blob/main/docs%2FREADME.md

**Comment by cx4** [comment]
> https://github.com/McGill-NLP/webllama/blob/main/docs%2FREADME.md

Thank you for your answer. Maybe my comprehension is not good enough. It bothers me to go from one readme file to another readme file. Could you provide a simpler Tutorial?

**Comment by cx4** [comment]
> https://github.com/McGill-NLP/webllama/blob/main/docs%2FREADME.md

```Traceback (most recent call last):  File "G:\free_project\webllama\webllama-main\examples\complete\run_all.py", line 5, in <module>
    from sentence_transformers import SentenceTransformer
  File "G:\free_project\webllama\webllama-iuB1fxj9\Lib\site-packages\sentence_transformers\__init__.py", line 15, in <module>
    from sentence_transformers.trainer import SentenceTransformerTrainer
  File "G:\free_project\webllama\webllama-iuB1fxj9\Lib\site-packages\sentence_transformers\trainer.py", line 10, in <module>
    from transformers import EvalPrediction, PreTrainedTokenizerBase, Trainer, TrainerCallback
  File "G:\free_project\webllama\webllama-iuB1fxj9\Lib\site-packages\transformers\utils\import_utils.py", line 1525, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "G:\free_project\webllama\webllama-iuB1fxj9\Lib\site-packages\transformers\utils\import_utils.py", line 1535, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "D:\Python\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "G:\free_project\webllama\webllama-iuB1fxj9\Lib\site-packages\transformers\trainer.py", line 71, in <module>
    from .optimization import Adafactor, get_scheduler
  File "G:\free_project\webllama\webllama-iuB1fxj9\Lib\site-packages\transformers\optimization.py", line 27, in <module>
    from .trainer_pt_utils import LayerWiseDummyOptimizer, LayerWiseDummyScheduler
  File "G:\free_project\webllama\webllama-iuB1fxj9\Lib\site-packages\transformers\trainer_pt_utils.py", line 235, in <module>
    device: Optional[torch.device] = torch.device("cuda"),
G:\free_project\webllama\webllama-iuB1fxj9\Lib\site-packages\transformers\trainer_pt_utils.py:235: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at ..\torch\csrc\utils\tensor_numpy.cpp:84.)
  device: Optional[torch.device] = torch.device("cuda"),
Traceback (most recent call last):
  File "G:\free_project\webllama\webllama-main\examples\complete\run_all.py", line 16, in <module>
    replay = wl.Replay.from_demonstration(demos[0])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\free_project\webllama\webllama-iuB1fxj9\Lib\site-packages\weblinx\__init__.py", line 1093, in from_demonstration
    replay = demonstration.replay
             ^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "G:\free_project\webllama\webllama-iuB1fxj9\Lib\site-packages\weblinx\__init__.py", line 98, in replay
    return self.load_json("replay.json")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\free_project\webllama\webllama-iuB1fxj9\Lib\site-packages\weblinx\__init__.py", line 176, in load_json
    results = utils.auto_read_json(self.path / filename, backend=backend, encoding=encoding)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\free_project\webllama\webllama-iuB1fxj9\Lib\site-packages\weblinx\utils\__init__.py", line 196, in auto_read_json
    data = json.load(f)
           ^^^^^^^^^^^^
  File "D:\Python\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
                 ^^^^^^^^^
UnicodeDecodeError: 'gbk' codec can't decode byte 0x99 in position 508322: illegal multibyte sequence```

**Comment by xhluca** [comment]
It seems you are using windows, which we do not recommend as we have not tested on this OS. Feel free to use WSL, Mac or Ubuntu.
